version: "3.9"

services:
  fractal-redis:
    image: redis:alpine3.16
    ports:
      - "6379:6379"
    networks:
      - fractal-backend

  fractal-api:
    build:
      context: .
      target: prod
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app
    networks:
      - fractal-backend
    env_file:
      - .env

  fractal-sync:
    build:
      context: .
      target: sync
    volumes:
      - ./:/app
    networks:
      - fractal-backend
    env_file:
      - .env

networks:
  fractal-backend:
